import type { DashboardData } from "./types"

/**
 * Mock dataset used to render the dashboard before the live FastAPI backend is wired up.
 * The shape of this object matches exactly what `GET /v1/dashboard` should return,
 * so swapping `getDashboardData()` for a real `fetch()` is a drop-in replacement.
 */
export const mockDashboardData: DashboardData = {
  metrics: {
    totalDevices: 1284,
    totalSoftwareAssets: 8736,
    complianceAlerts: 47,
    potentialSavings: 184250,
  },
  devices: [
    {
      id: "dev-001",
      deviceName: "FIN-WS-0142",
      os: "Windows",
      ipAddress: "10.4.12.87",
      lastAudit: "2026-06-08T09:14:00Z",
      status: "active",
    },
    {
      id: "dev-002",
      deviceName: "ENG-LNX-0031",
      os: "Linux",
      ipAddress: "10.4.20.14",
      lastAudit: "2026-06-08T08:52:00Z",
      status: "active",
    },
    {
      id: "dev-003",
      deviceName: "HR-WS-0088",
      os: "Windows",
      ipAddress: "10.4.12.41",
      lastAudit: "2026-06-07T22:03:00Z",
      status: "offline",
    },
    {
      id: "dev-004",
      deviceName: "OPS-LNX-0007",
      os: "Linux",
      ipAddress: "10.4.20.02",
      lastAudit: "2026-06-08T09:01:00Z",
      status: "active",
    },
    {
      id: "dev-005",
      deviceName: "SALES-WS-0210",
      os: "Windows",
      ipAddress: "10.4.13.110",
      lastAudit: "2026-06-08T07:46:00Z",
      status: "active",
    },
    {
      id: "dev-006",
      deviceName: "DEV-LNX-0119",
      os: "Linux",
      ipAddress: "10.4.21.55",
      lastAudit: "2026-06-06T18:30:00Z",
      status: "offline",
    },
    {
      id: "dev-007",
      deviceName: "EXEC-WS-0003",
      os: "Windows",
      ipAddress: "10.4.10.03",
      lastAudit: "2026-06-08T09:20:00Z",
      status: "active",
    },
    {
      id: "dev-008",
      deviceName: "QA-LNX-0064",
      os: "Linux",
      ipAddress: "10.4.21.88",
      lastAudit: "2026-06-08T06:12:00Z",
      status: "active",
    },
  ],
  software: [
    {
      id: "sw-001",
      applicationName: "Microsoft Office 365",
      version: "16.0.17328",
      totalInstallations: 842,
      licenseType: "Subscription",
      complianceStatus: "Over-licensed",
    },
    {
      id: "sw-002",
      applicationName: "Adobe Photoshop",
      version: "25.9.0",
      totalInstallations: 112,
      licenseType: "Subscription",
      complianceStatus: "Unlicensed",
    },
    {
      id: "sw-003",
      applicationName: "Google Chrome",
      version: "126.0.6478",
      totalInstallations: 1190,
      licenseType: "Freeware",
      complianceStatus: "Compliant",
    },
    {
      id: "sw-004",
      applicationName: "Slack",
      version: "4.38.121",
      totalInstallations: 654,
      licenseType: "Commercial",
      complianceStatus: "Compliant",
    },
    {
      id: "sw-005",
      applicationName: "JetBrains IntelliJ IDEA",
      version: "2026.1.2",
      totalInstallations: 88,
      licenseType: "Subscription",
      complianceStatus: "Over-licensed",
    },
    {
      id: "sw-006",
      applicationName: "VLC Media Player",
      version: "3.0.20",
      totalInstallations: 433,
      licenseType: "Open Source",
      complianceStatus: "Compliant",
    },
    {
      id: "sw-007",
      applicationName: "Autodesk AutoCAD",
      version: "2026.1",
      totalInstallations: 41,
      licenseType: "Commercial",
      complianceStatus: "Unlicensed",
    },
    {
      id: "sw-008",
      applicationName: "Docker Desktop",
      version: "4.31.0",
      totalInstallations: 207,
      licenseType: "Commercial",
      complianceStatus: "Over-licensed",
    },
    {
      id: "sw-009",
      applicationName: "Mozilla Firefox",
      version: "127.0.1",
      totalInstallations: 318,
      licenseType: "Open Source",
      complianceStatus: "Compliant",
    },
    {
      id: "sw-010",
      applicationName: "Zoom Workplace",
      version: "6.0.11",
      totalInstallations: 720,
      licenseType: "Commercial",
      complianceStatus: "Compliant",
    },
  ],
}
